from collections.abc import MutableMapping
from datetime import date, datetime
from enum import Enum
from pathlib import PurePath, PurePosixPath, PureWindowsPath

# TODO: Use RunEngineMetadata from bluesky.run_engine when it is available in released version
# from bluesky.run_engine import RunEngineMetadata
from typing import Any
from urllib.parse import urlunparse
from ophyd_async.core import (
    FilenameProvider,
    PathProvider,
    PathInfo,
    UUIDFilenameProvider,
)
import os


class YMDGranularity(int, Enum):
    """Enum for specifying the granularity of the year/month/day portion of the path generated by NSLS2PathProvider.

    Attributes
    ----------
    none : int
        No granularity, do not include year/month/day in the path.
    year : int
        Include only the year in the path.
    month : int
        Include the year and month in the path.
    day : int
        Include the year, month, and day in the path.
    """

    none = 0
    year = 1
    month = 2
    day = 3


class TimestampFilenameProvider(FilenameProvider):
    """Filename provider that generates filenames based on the current timestamp.

    Parameters
    ----------
    timestamp_format : str, default "%Y%m%d_%H%M%S"
        Format string passed to `datetime.now().strftime()`.
    """

    def __init__(self, timestamp_format: str = "%Y%m%d_%H%M%S"):
        self._timestamp_format = timestamp_format

    def __call__(self, datakey_name: str | None = None) -> str:
        """Generates a filename based on the current timestamp and optionally the datakey name.

        Parameters
        ----------
        datakey_name : str, optional
            The name of the datakey to include in the filename. Only used if include_datakey_name is True.

        Returns
        -------
        str
            The generated filename.
        """

        timestamp = datetime.now().strftime(self._timestamp_format)
        if datakey_name is not None:
            return f"{datakey_name}_{timestamp}"
        return timestamp


class REMetadataFilenameProvider(TimestampFilenameProvider):
    """Filename provider that generates filenames based on the current timestamp and the RE metadata.

    Parameters
    ----------
    format_string : str
        Format string used to generate the filename. The format string can include placeholders for keys in the metadata dictionary.
    timestamp_format : str
        Format string passed to `datetime.now().strftime()`.
    metadata_dict : dict
        Typically `RE.md`. Used for dynamic save path generation from sync-d experiment
    separator : str, default "_"
        Separator to use between the datakey name, formatted metadata, and timestamp in the filename.
    include_timestamp : bool, default True
        Whether to include the timestamp in the filename. If False, only the datakey name and formatted metadata will be included.
    prepend_datakey_name : bool, default True
        Whether to prepend the datakey name to the filename. If False, only the formatted metadata and timestamp will be included.
    """

    def __init__(
        self,
        format_string: str,
        timestamp_format: str,
        metadata_dict: MutableMapping[str, Any],
        separator: str = "_",
        include_timestamp: bool = True,
        prepend_datakey_name: bool = True,
    ):
        self._format_string = format_string
        self._metadata_dict = metadata_dict
        self._separator = separator
        self._include_timestamp = include_timestamp
        self._prepend_datakey_name = prepend_datakey_name
        super().__init__(timestamp_format=timestamp_format)

    @property
    def format_string(self) -> str:
        """Returns the format string used for generating filenames."""

        return self._format_string

    def __call__(self, datakey_name: str | None = None) -> str:
        """Generates a filename based on the current timestamp and the RE metadata.

        Parameters
        ----------
        datakey_name : str, optional
            The name of the datakey to include in the filename. Only used if include_datakey_name is True.

        Returns
        -------
        str
            The generated filename.
        """

        parts = [self._format_string.format(**self._metadata_dict)]
        if datakey_name is not None and self._prepend_datakey_name:
            parts.insert(0, datakey_name)
        if self._include_timestamp:
            parts.append(super().__call__())
        return self._separator.join(parts)


def _drive_letter_to_path(drive_letter: str) -> PureWindowsPath:
    """Normalizes a drive letter to uppercase and ensures it ends with a colon.

    Parameters
    ----------
    drive_letter : str
        The drive letter to normalize.

    Returns
    -------
    PureWindowsPath
        The normalized drive letter, as a PureWindowsPath object.
    """

    # If more than one character is provided and the second character is a colon,
    # take only the first character
    if len(drive_letter) > 1 and drive_letter[1] == ":":
        drive_letter = drive_letter[0]

    # Drive letter at this point must be a single character, and it must be an alphabetic character
    if len(drive_letter) != 1 or not drive_letter.isalpha():
        raise ValueError("Drive letter must be a single alphabetic character.")

    return PureWindowsPath(f"{drive_letter.upper()}:\\")


class NSLS2PathProvider(PathProvider):
    """Default NSLS2 path provider.

    Generates paths in the following format:

    /nsls2/data/{TLA}/proposals/{CYCLE}/{PROPOSAL}/assets/{DETECTOR}/{Y}/{M}/{D}

    If include_scan_id_dir is provided, an additional directory will be created at the
    end of the path with the name scan_{scan_id:06}.

    Parameters
    ----------
    metadata_dict : MutableMapping[str, Any]
        Typically `RE.md`. Used for dynamic save path generation from sync-d experiment
    filename_provider : FilenameProvider, default UUIDFilenameProvider()
        Filename provider to use for generating filenames. Defaults to UUIDs.
    beamline_data_dirname : str, optional
        Name of the beamline data directory to use in the path, typically lowercase beamline TLA.
        If not provided, the name will be determined from the ENDSTATION_ACRONYM or
        BEAMLINE_ACRONYM environment variables.
    separator : str, optional
        Separator to use in YMD portion of the path. Defaults to default path separator given write directory semantics.
    granularity : YMDGranularity | str, default YMDGranularity.day
        Granularity of the YMD portion of the path. If set to YMDGranularity.day, the path will include year, month,
        and day directories. If set to YMDGranularity.month, the path will include year and month directories.
        If set to YMDGranularity.year, the path will include only the year directory.
    include_scan_id_dir : bool, default False
        Whether to include a scan ID directory at the end of the path.
    """

    def __init__(
        self,
        metadata_dict: MutableMapping[str, Any],
        filename_provider: FilenameProvider = UUIDFilenameProvider(),
        granularity: YMDGranularity | str = YMDGranularity.day,
        windows_drive_letter: str | None = None,
        separator: str | None = None,
        beamline_data_dirname: str | None = None,
        include_scan_id_dir: bool = False,
    ):

        self._filename_provider = filename_provider
        self._metadata_dict = metadata_dict
        self._granularity = granularity if isinstance(granularity, YMDGranularity) else YMDGranularity[granularity]
        self._base_read_directory = self._get_beamline_proposals_dir(beamline_data_dirname=beamline_data_dirname)
        self._base_write_directory = (
            self._base_read_directory
            if not windows_drive_letter
            else _drive_letter_to_path(windows_drive_letter) / "proposals"
        )
        self._ymd_separator = separator or "\\" if windows_drive_letter else os.path.sep
        self._include_scan_id_dir = include_scan_id_dir

    @property
    def filename_provider(self) -> FilenameProvider:
        """Returns the filename provider used by this path provider."""

        return self._filename_provider

    def _get_beamline_proposals_dir(self, beamline_data_dirname: str | None = None) -> PurePosixPath:
        """
        Function that computes path to the proposals directory based on TLA env vars
        """

        beamline_data_dirname = (
            beamline_data_dirname or os.getenv("ENDSTATION_ACRONYM", os.getenv("BEAMLINE_ACRONYM", "")).lower()
        )

        beamline_proposals_dir = PurePosixPath(f"/nsls2/data/{beamline_data_dirname}/proposals/")

        return beamline_proposals_dir

    def _generate_directory_path(self, base_path: PurePath, datakey_name: str) -> PurePath:
        """Helper function that generates ymd path structure.

        Depending on the granularity, the path will include year, month, and day directories.
        If the include_scan_id_dir is provided, an additional directory will be created at the end of the
        path with the name scan_{scan_id:06}.

        Parameters
        ----------
        base_path : PurePath
            The base path to which the YMD portion of the path will be appended.
        datakey_name : str
            The name of the datakey to include in the path.

        Returns
        -------
        PurePath
            The generated directory path.

        Raises
        ------
        KeyError
            If the metadata dictionary does not contain the required keys 'cycle' and 'data_session'.
        """

        path_semantics = type(base_path)

        # Given requested granularity, construct the current date template string to be used in the path.
        if self._granularity >= YMDGranularity.day:
            current_date_template = f"%Y{self._ymd_separator}%m{self._ymd_separator}%d"
        elif self._granularity == YMDGranularity.month:
            current_date_template = f"%Y{self._ymd_separator}%m"
        elif self._granularity == YMDGranularity.year:
            current_date_template = f"%Y{self._ymd_separator}"
        elif self._granularity == YMDGranularity.none:
            current_date_template = ""

        ymd_dir_path = path_semantics(datakey_name) / date.today().strftime(current_date_template)

        directory_path = (
            base_path
            / str(self._metadata_dict["cycle"])
            / str(self._metadata_dict["data_session"])
            / "assets"
            / ymd_dir_path
        )

        if self._include_scan_id_dir:
            directory_path = directory_path / f"scan_{self._metadata_dict['scan_id']:06}"

        return directory_path

    def __call__(self, datakey_name) -> PathInfo:
        """Generates a PathInfo object containing the directory path and filename for the current acquisition.

        Parameters
        ----------
        datakey_name : str
            The name of the datakey to include in the path.

        Returns
        -------
        PathInfo
            The generated PathInfo object.
        """

        if "cycle" not in self._metadata_dict or "data_session" not in self._metadata_dict:
            raise KeyError("Metadata dictionary must contain 'cycle' and 'data_session' keys!")

        full_write_path = self._generate_directory_path(self._base_write_directory, datakey_name=datakey_name)
        full_read_path = self._generate_directory_path(self._base_read_directory, datakey_name=datakey_name)

        return PathInfo(
            directory_path=full_write_path,
            directory_uri=urlunparse(
                (
                    "file",
                    "localhost",
                    f"{full_read_path.as_posix()}/",
                    "",
                    "",
                    "",
                )
            ),
            filename=self._filename_provider(),
            create_dir_depth=-self._granularity - (1 if self._include_scan_id_dir else 0),
        )
